- hosts: localhost
  sudo: yes
  remote_user: vagrant
  tasks:
  - name: Actualizar sistema base
    apt: update_cache=yes upgrade=dist
  - name: Instalar git
    action: apt pkg=git state=installed
  - name: Install Python Pip
    action: apt pkg=python-pip state=installed
  - name: Obtener aplicacion de git
    git: repo=https://github.com/hugobarzano/DAIproducion.git  dest=~/DAIproducion clone=yes force=yes
  - name: Dar permisos de ejecucion
    command: chmod -R +x ~/DAIproducion
  - name: Instalar docker y docker-compose
    command: sh ~/DAIproducion/deploy_docker.sh
  - name: Descargar imagen necesaria
    command: service docker restart
    command: docker pull hugobarzano/daiproducion
  - name: Enrrutamiento
    command: sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j DNAT --to-destination 172.17.0.1:80
    command: sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j DNAT --to-destination 172.17.0.2:80
    command: sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j DNAT --to-destination 172.17.0.3:80
  - name: Ejecutar
    command: sudo docker run -t -i hugobarzano/daiproducion sh -c "ifconfig && cd /DAIproducion &&  python manage.py makemigrations --noinput && python manage.py migrate --noinput && python manage.py syncdb --noinput && sudo python manage.py runserver 0.0.0.0:80"
